name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        pip3 install wheel
        sudo apt-get install python3-setuptools
        pip3 install pytest numpy setuptools tensorflow dill tensorflow-metadata
        git clone https://github.com/rushabh-v/datasets
        cd datasets
        git checkout bair_large
        python -m tensorflow_datasets.scripts.download_and_prepare \
        --register_checksums \
        --datasets=bair_robot_pushing128

        
        
