name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - name: Installaion
      run: |
        sudo apt update
        sudo add-apt-repository ppa:rushabh-v/facerec
        sudo apt install facerec



# name: CI

# on: [push]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Test TFDS
#       run: |
#         pip3 install wheel
#         sudo apt-get install python3-setuptools
#         pip3 install pytest numpy promise setuptools typing typeguard>=2.7 tensorflow==2.0.0b1 dill tqdm tensorflow-metadata
#         git clone https://github.com/rushabh-v/datasets
#         cd datasets
#         git checkout bair_large
#         python3 -m tensorflow_datasets.scripts.download_and_prepare \
#         --register_checksums \
#         --datasets=bair_robot_pushing128

        
        
